export const products = [
    {
        id : 0,
        name : 'Hublot Classic Fusion Ceramic Blue Chronograph 42mm 541.CM.7170.RX',
        price : '$'+ 13000,
        retailPrice : '$'+ 14000,
        imgProduct : 'watchesImg/hublot(1).png',
        hiddenImgProduct: 'watchesImg/hublot(2).png',
        img3 : 'watchesImg/hublot(3).png',
        img4 : 'watchesImg/hublot(4).png',
        conditition : 100 + '%',
        accessories : 'Box, book, 2020 warranty card',
        size : 42 +'mm',
        brand : 'Hublot',
        movement : 'Caliber HUB1143',
        ref : '541.cm.7170.rx',
        function : 'Hours, minutes, seconds, chronograph',
        powerReserve: 48 + ' hours',
        material : 'Titanium',
        waterResistant : 50+'m'
    },
    {
        id : 1,
        name : 'Rolex GMT-Master II 126710BLNR',
        price : '$'+ 24900,
        retailPrice : '$'+ 27000,
        imgProduct : 'watchesImg/rolex.png',
        hiddenImgProduct: 'watchesImg/rolex2.png',
        img3 : 'watchesImg/rolex3.png',
        img4 : 'watchesImg/rolex4.png',
        conditition : 100 + '%',
        accessories : '	Box, book, June 2022 warranty card',
        size : 40 +'mm',
        brand : 'Rolex',
        movement : 'Automatic, Cal.3285',
        ref : '126710BLNR-0002',
        function : 'Dates, hours, minutes, seconds, GMT',
        powerReserve: 70 + ' hours',
        material : 'Stainless steel',
        waterResistant : 100+'m'
    },
    {
        id : 2,
        name : 'Jacob & Co Epic X Chrono Black Titanium Ceramic Bezel EC400.21.AB.AB.A',
        price : '$'+21900,
        retailPrice : '$'+25000,
        imgProduct : 'watchesImg/jacob&co.png',
        hiddenImgProduct: 'watchesImg/jacob&co(1).png',
        img3 : 'watchesImg/jacob&co(2).png',
        img4 : 'watchesImg/jacob&co(3).png',
        conditition : 100 + '%',
        accessories : 'Box, book, 2022 warranty card',
        size : 43 +'mm',
        brand : 'Jacob & Co',
        movement : 'Automatic, Cal JCAA05',
        ref : 'EC400.21.AB.AB.A',
        function : 'Hours, minutes, seconds, chronograph',
        powerReserve: 48 + ' hours',
        material : 'Black DLC Grade 5 Titanium; Black Ceramic Bezel',
        waterResistant : 100+'m'
    },
    {
        id : 3,
        name : 'Patek Philippe Complications 5230P-001',
        price : '$'+46900,
        retailPrice : '$'+50000,
        imgProduct : 'watchesImg/patek(1).png',
        hiddenImgProduct: 'watchesImg/patek.png',
        img3 : 'watchesImg/patek(2).png',
        img4 : 'watchesImg/patek(3).png',
        conditition : 100 + '%',
        accessories : 'Box, book, 2022 warranty card',
        size : 38.5 +'mm',
        brand : 'Patek Philippe',
        movement : 'Automatic, Cal 240 HU',
        ref : '5230P-001',
        function : 'Hours, minutes, seconds, moon phase, GMT',
        powerReserve: 48 + ' hours',
        material : 'Platinum, Sapphire-crystal',
        waterResistant : 30+'m'
    },
    {
        id : 4,
        name : 'Cartier Santos Large Skeleton WHSA0015',
        price : '$'+28900,
        retailPrice : '$'+30900,
        imgProduct : 'watchesImg/cartier(2).png',
        hiddenImgProduct: 'watchesImg/cartier(1).png',
        img3 : 'watchesImg/cartier(3).png',
        img4 : 'watchesImg/cartier(4).png',
        conditition : 100 + '%',
        accessories : 'Box, book, 2022 warranty card',
        size : 39.8 +'mm',
        brand : 'Cartier',
        movement : 'Manual winding, Cal 9611 MC',
        ref : 'WHSA0015',
        function : 'Hours, minutes',
        powerReserve: 72 + ' hours',
        material : 'Stainless Steel',
        waterResistant : 100+'m'
    },
    {
        id : 5,
        name : 'Chopard Happy Sport 278573-6013',
        price : '$'+6900,
        retailPrice : '$'+7490,
        imgProduct : 'watchesImg/chopard.png',
        hiddenImgProduct: 'watchesImg/chopard(1).png',
        img3 : 'watchesImg/chopard(2).png',
        img4 : 'watchesImg/chopard(3).png',
        conditition : 100 + '%',
        accessories : 'Box, book, 2021 warranty card',
        size : 42 +'mm',
        brand : 'Chopard',
        movement : 'Automatic, Cal Chopard 09.01-C',
        ref : '278573-6013',
        function : 'Hours, minutes, seconds',
        powerReserve: 42 + ' hours',
        material : '18-carat rose gold, stainless steel',
        waterResistant : 30+'m'
    },
    {
        id : 6,
        name : 'Omega Constellation 39mm 131.53.39.20.03.001',
        price : '$'+24900,
        retailPrice : '$'+26900,
        imgProduct : 'watchesImg/omega1.png',
        hiddenImgProduct: 'watchesImg/omega2.png',
        img3 : 'watchesImg/omega3.png',
        img4 : 'watchesImg/omega4.png',
        conditition : 100 + '%',
        accessories : 'Box, book, 2023 warranty card',
        size : 39 +'mm',
        brand : 'Omega',
        movement : 'Automatic, Cal 8801',
        ref : '131.53.39.20.03.001',
        function : 'Hours, minutes, seconds, days',
        powerReserve: 55 + ' hours',
        material : '18-carat rose gold',
        waterResistant : 50+'m'
    },
    {
        id : 7,
        name : 'Piaget Altiplano G0A41011',
        price : '$'+22900,
        retailPrice : '$'+25000,
        imgProduct : 'watchesImg/piaget.png',
        hiddenImgProduct: 'watchesImg/piaget(3).png',
        img3 : 'watchesImg/piaget(2).png',
        img4 : 'watchesImg/piaget(3).png',
        conditition : 100 + '%',
        accessories : 'Box, book, 2020 warranty card',
        size : 38 +'mm',
        brand : 'Piaget',
        movement : 'Manual winding, Cal 900P',
        ref : 'G0A41011',
        function : 'Hours, minutes, seconds',
        powerReserve: 48 + ' hours',
        material : '18-carat rose gold',
        waterResistant : 20+'m'
    },
]

        